### ISSUE TITLE
Source code link is not accessible

### ISSUE THREAD

**Issue by paparaju** [ymhmd/API-Testing-Automation-Framework#3]
Hey,

The source code link pointed in the READ ME is not acceisble : https://github.com/ymhmd/API-Testing-Automation-Framework-SourceCode. Can you please update readme with right source code link.

**Comment by ymhmd** [comment]
Thanks @paparaju for submitting the issue.

Updated the readme with the correct source code - https://github.com/ymhmd/buenoAPI-SourceCode

**Comment by ymhmd** [comment]
Closed the issue after updating the readme file 🚀
